services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/horilla"
      DISABLE_COMPANY_MW: "1"
      ALLOWED_HOSTS: "localhost,127.0.0.1,horillademo.swyftbridge.io,eks4goc8s84844s4w0wgc48k.contextra.io"
      CSRF_TRUSTED_ORIGINS: "https://horillademo.swyftbridge.io,https://eks4goc8s84844s4w0wgc48k.contextra.io"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 5s
      retries: 5
    entrypoint: ["/app/entrypoint.sh"]
    volumes:
      - media:/app/media
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-bullseye
    environment:
      POSTGRES_DB: horilla
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - horilla-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  media:
    driver: local
  horilla-data:
